project:
  type: website

website:
  title: "DZ Stat"
  back-to-top-navigation: true
  reader-mode: true

  # repo-url: https://github.com/quarto-dev/quarto-demo
  # repo-actions: [edit, source, issue]

  page-footer:
    border: true
    center: 
      - text: "Copyright 2024, Mohamed Heddar"
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/
  
  navbar:
    logo: assets/logo.png
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Chapters"
        href: chapters.qmd
      - text: "References"
        href: references.qmd
      - text: "Contributing"
        href: contrib.qmd
      
    right:
    - text: "About"
      href: about.qmd
  
  sidebar:
    - title: "Chapters"
      style: "docked"
      background: light
      contents:
        - chapters.qmd
        - auto: Chapters
      tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com



      
format:
  html:
    theme:
      light: default
      dark: darkly
    css: styles.css
    toc: true



